# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_change', models.CharField(max_length=100)),
                ('BRS_num', models.IntegerField()),
                ('author', models.CharField(max_length=40)),
                ('author_email_address', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=40)),
                ('summary', models.TextField()),
                ('delivery_date', models.DateTimeField()),
                ('channels', models.CharField(max_length=10)),
                ('brands', models.CharField(max_length=40)),
                ('business_area', models.CharField(max_length=40)),
                ('allocated_date', models.DateTimeField(editable=False)),
                ('allocated', models.CharField(max_length=40)),
                ('point', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('raised', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_change', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('author_email_address', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=40)),
                ('summary', models.TextField()),
                ('delivery_date', models.DateTimeField()),
                ('channels', models.CharField(max_length=10)),
                ('brands', models.CharField(max_length=40)),
                ('business_area', models.CharField(max_length=40)),
                ('allocated_date', models.DateTimeField(editable=False)),
                ('allocated_to', models.CharField(max_length=40)),
                ('allocated', models.BooleanField(default=False)),
                ('point', models.IntegerField()),
                ('raised', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clockwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_change', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('author_email_address', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=40)),
                ('summary', models.TextField()),
                ('delivery_date', models.DateTimeField()),
                ('channels', models.CharField(max_length=10)),
                ('brands', models.CharField(max_length=40)),
                ('business_area', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=10)),
                ('raised', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened', models.BooleanField(default=True)),
                ('hold', models.BooleanField(default=False)),
                ('inprogress', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qu_BRS_num', to='dashboard.Changes')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField()),
                ('when', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_BRS_num', to='dashboard.Changes')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_author', to='dashboard.Changes')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_status', to='dashboard.Changes')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_title', to='dashboard.Queries'),
        ),
    ]
