# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='status',
            field=models.CharField(choices=[('op', 'Open'), ('st', 'Started'), ('im', 'Implemented'), ('ab', 'Abadonded'), ('ho', 'On Hold')], default='Open', max_length=10),
        ),
    ]
