# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170126_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='allocated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cir',
            name='allocated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cir',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clockwork',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
