# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glob_obj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalobjects',
            name='modified_by',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
