# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 15:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consigments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_code', models.CharField(max_length=40, verbose_name='Letter code')),
                ('letter_BG', models.BooleanField(default=False, verbose_name='BG')),
                ('letter_SG', models.BooleanField(default=False, verbose_name='SG')),
                ('letter_SE', models.BooleanField(default=False, verbose_name='SE')),
                ('email_BG', models.BooleanField(default=False, verbose_name='BG')),
                ('email_SE', models.BooleanField(default=False, verbose_name='SE')),
                ('vi', models.CharField(choices=[(b'N', b'New'), (b'O', b'Old')], max_length=1, verbose_name='VI')),
                ('environment', models.CharField(choices=[(b'G', b'GMC'), (b'H', b'HP')], max_length=1, verbose_name='Environment')),
                ('comments', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('modified_by', models.CharField(max_length=30, verbose_name='Modified by')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consigments.Applications', verbose_name='Application')),
                ('business_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consigments.Areas', verbose_name='Business area')),
            ],
        ),
        migrations.CreateModel(
            name='Journeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='consigments',
            name='journey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consigments.Journeys', verbose_name='Journey'),
        ),
    ]
