# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consigments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_code', models.CharField(max_length=40)),
                ('letter_BG', models.BooleanField(default=False)),
                ('letter_SG', models.BooleanField(default=False)),
                ('letter_SE', models.BooleanField(default=False)),
                ('email_BG', models.BooleanField(default=False)),
                ('email_SE', models.BooleanField(default=False)),
                ('application', models.CharField(max_length=10)),
                ('journey', models.CharField(max_length=10)),
                ('vi', models.CharField(max_length=3)),
                ('environment', models.CharField(max_length=3)),
                ('comments', models.TextField()),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
