# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consigments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='consigments',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consigments.Applications', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='comments',
            field=models.TextField(verbose_name='Letter code'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='email_BG',
            field=models.BooleanField(default=False, verbose_name='BG'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='email_SE',
            field=models.BooleanField(default=False, verbose_name='SE'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='environment',
            field=models.CharField(choices=[('G', 'GMC'), ('H', 'HP')], max_length=1, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='journey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consigments.Journeys', verbose_name='Journey'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='letter_BG',
            field=models.BooleanField(default=False, verbose_name='BG'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='letter_SE',
            field=models.BooleanField(default=False, verbose_name='SE'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='letter_SG',
            field=models.BooleanField(default=False, verbose_name='SG'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='letter_code',
            field=models.CharField(max_length=40, verbose_name='Letter code'),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='consigments',
            name='vi',
            field=models.CharField(choices=[('N', 'New'), ('O', 'Old')], max_length=1, verbose_name='VI'),
        ),
    ]
