# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consigments', '0002_auto_20161230_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consigments',
            name='comments',
            field=models.TextField(verbose_name='Comments'),
        ),
    ]
