# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consigments', '0004_auto_20170101_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consigments',
            name='modified_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
