# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consigments', '0005_auto_20170101_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consigments',
            name='modified_by',
            field=models.CharField(max_length=30, verbose_name='Modified by'),
        ),
    ]
