# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consigments', '0007_auto_20170102_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consigments',
            name='business_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consigments.Areas', verbose_name='Business area'),
        ),
    ]
