# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 19:34
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('consigments', '0008_auto_20170102_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consigments',
            name='comments',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
